spring:
  application:
    name: languagecoach
groq:
  api-key: ${GROQ_API_KEY:}
  base-url: ${GROQ_BASE_URL:https://api.groq.com/openai/v1}
  speech-to-text:
    model: ${GROQ_SPEECH_TO_TEXT_MODEL:whisper-large-v3-turbo}
  text:
    model: ${GROQ_TEXT_MODEL:meta-llama/llama-4-scout-17b-16e-instruct}
openai:
  api-key: ${OPENAI_API_KEY:}
  speech-to-text:
    model: ${OPENAI_SPEECH_TO_TEXT_MODEL:gpt-4o-mini-transcribe}
  text:
    model: ${OPENAI_TEXT_MODEL:gpt-4.1}